name: GeneratePlantumlImages

on:
  push:
    branches: [ '**' ]
    paths: [ '.github/workflows/GeneratePlantumlImages.yml', 'src/plantuml/**', 'images/diagrams/**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: gematik/github-image-actions/.github/workflows/generate-images.yml@92102d1ae89eee14cdc918b370eda67a63b2ce1a
    with:
      srcdir: src/plantuml
      outdir: images/diagrams
      ref: 92102d1ae89eee14cdc918b370eda67a63b2ce1a
      png: true
      svg: true
